/* ── Polskie nazwy zdarzeń dziennika (0.540.0) ─────────────────────────
   Decyzja właściciela z 27 września 2026, wariant C z makiet. Kolumna
   zdarzenia pokazywała klucz serwera — `putaway_line_done`, `queue_failed` —
   a biuro miało go rozszyfrować samo. Dekalog p. 2: rozpoznanie tańsze od
   pamiętania.

   JEDNA NAZWA NA KAŻDY TYP Z REJESTRU. Lista typów stoi na serwerze
   w `services/zdarzenia-rejestr.ts` i pilnuje jej tamtejszy test. Ten plik
   pilnuje `nazwy.test.ts`: typ z rejestru bez polskiej nazwy to czerwony
   test, nie klucz wracający na ekran po cichu.

   KLUCZ NIE ZNIKA. Stoi w dymku pastylki, w CSV i w filtrze „Co" jako
   wartość, bo po nim szuka się w eksporcie i w kodzie. Typ spoza rejestru
   — stary albo dopisany bez wpisu — pokazuje się surowym kluczem. */

export const NAZWA_ZDARZENIA: Record<string, string> = {
  /* Kolektor: skany, półki, odkładanie */
  scan: "Skan",
  scan_timing: "Pomiar czasu skanu",
  manual_entry: "Kod wpisany ręcznie",
  search: "Szukanie na kolektorze",
  location_set: "Lokalizacja ustawiona",
  location_removed: "Lokalizacja zdjęta",
  location_mismatch: "Inna półka niż w kartotece",
  przesuniecie: "Przesunięcie między magazynami",
  putaway_line_done: "Odłożenie pozycji",
  putaway_cofniete: "Odłożenie cofnięte",
  putaway_polka_zmieniona: "Półka odłożenia zmieniona",
  putaway_qty_fixed: "Ilość odłożenia poprawiona",
  ean_set: "Kod kreskowy przypisany",
  ean_conflict: "Kolizja kodu kreskowego",
  ean_conflict_autoresolved: "Kolizja kodu rozstrzygnięta sama",
  ean_kolizja_rozstrzygnieta: "Kolizja kodu rozstrzygnięta przez biuro",
  zdjecie_dodane: "Zdjęcie dodane",
  problem_raised: "Problem zgłoszony",
  problem_resolved: "Problem rozwiązany",
  problem_wycofany: "Problem wycofany",
  karton_zalozony: "Karton założony",
  karton_pozycja: "Pozycja w kartonie",
  karton_pozycja_usunieta: "Pozycja zdjęta z kartonu",
  karton_ilosc: "Ilość w kartonie zmieniona",
  karton_zatwierdzony: "Karton zatwierdzony",
  karton_anulowany: "Karton anulowany",
  device_drop: "Upadek kolektora",
  battery_low: "Słaba bateria kolektora",
  siec_przerwa: "Przerwa w łączności kolektora",
  czasy_zadan: "Pomiar czasów odpowiedzi",
  http_rejected: "Serwer odrzucił żądanie",
  klient_odrzucona: "Kolektor nie wykonał operacji",
  kolektor_wezwany: "Kolektor wezwany",
  kolektor_wezwanie_odwolane: "Wezwanie kolektora odwołane",
  kolektor_odnaleziony: "Kolektor odnaleziony",

  /* Dostawy i przyjęcie */
  delivery_open: "Dostawa otwarta",
  delivery_done: "Dostawa zamknięta na kolektorze",
  delivery_finished: "Dostawa domknięta",
  delivery_reopened: "Dostawa otwarta ponownie",
  delivery_external: "Dostawa poza aplikacją",
  delivery_external_undo: "Dostawa poza aplikacją cofnięta",
  delivery_note_added: "Notatka do dostawy",
  delivery_note_answered: "Odpowiedź na notatkę do dostawy",
  notatka_odpowiedz_przeczytana: "Odpowiedź na notatkę przeczytana",
  przyjecie_otwarte: "Przyjęcie otwarte",
  przyjecie_poza_aplikacja: "Przyjęcie poza aplikacją",
  przesylka_zapisana: "Przesyłka zapisana",
  brak_na_serwis: "Brak zgłoszony na serwis",
  brak_na_serwis_pominiety: "Brak na serwis pominięty",

  /* Zapisy do Subiekta */
  queue_applied: "Zapis do Subiekta wszedł",
  queue_failed: "Zapis do Subiekta nie wszedł",
  queue_retry: "Zapis do Subiekta ponawiany",
  queue_ponowione_recznie: "Zapis ponowiony ręcznie",
  queue_anulowane_recznie: "Zapis anulowany ręcznie",

  /* Zadania terenowe */
  zadanie_terenowe_utworzone: "Zadanie terenowe zlecone",
  zadanie_terenowe_przejete: "Zadanie terenowe przejęte",
  zadanie_terenowe_wykonane: "Zadanie terenowe wykonane",
  zadanie_terenowe_oddane: "Zadanie terenowe oddane",
  zadanie_terenowe_odeslane: "Zadanie terenowe odesłane",
  zadanie_terenowe_ponowione: "Zadanie terenowe ponowione",
  zadanie_terenowe_anulowane: "Zadanie terenowe anulowane",
  zadanie_terenowe_zalacznik: "Załącznik do zadania terenowego",

  /* Kosze */
  kosz_putaway: "Odłożenie z kosza",
  kosz_putaway_cofniete: "Odłożenie z kosza cofnięte",
  kosz_putaway_poprawka: "Odłożenie z kosza poprawione",
  kosz_rozlozony: "Kosz rozłożony",
  kosz_zakonczenie_cofniete: "Zakończenie kosza cofnięte",
  kosz_powrot_mm: "Powrót MM z kosza",
  kosz_mm_ponowione: "MM kosza ponowione",
  kosz_mm_pozycja_zdjeta: "Pozycja zdjęta z MM kosza",
  kosz_pozycja_pominieta: "Pozycja kosza pominięta",
  kosz_pozycja_na_pozniej: "Pozycja kosza na później",
  kosz_pominiecie_zalatwione: "Pominięcie w koszu załatwione",
  kosz_pominiecie_cofniete: "Pominięcie w koszu cofnięte",
  kosz_zwrotow_otwarty: "Kosz zwrotów otwarty",
  kosz_zwrotow_zamkniety: "Kosz zwrotów zamknięty",
  kosz_zwrotow_usuniety: "Kosz zwrotów usunięty",
  kosz_zwrotow_wypuszczony: "Kosz zwrotów wypuszczony",
  kosz_zwrotow_przeliczony: "Kosz zwrotów przeliczony",
  kosz_zwrotow_dolozono: "Dołożono do kosza zwrotów",
  kosz_zwrotow_zdjeto: "Zdjęto z kosza zwrotów",
  kosz_zwrotow_skladnik: "Składnik kosza zwrotów",
  kosz_zwrotow_towar_dolozony: "Towar dołożony do kosza zwrotów",
  kosz_zwrotow_towar_zdjety: "Towar zdjęty z kosza zwrotów",
  kosz_zwrotow_zwiazany: "Kosz zwrotów związany ze zwrotem",
  kosz_zwrotow_zwiazanie_pominiete: "Wiązanie kosza pominięte",
  kosz_zwrotow_odmowa: "Odmowa w koszu zwrotów",
  kosz_zwrotow_mm_uniewazniona: "MM kosza zwrotów unieważniona",
  kosz_zwrotow_mm_mimo_korekt: "MM kosza mimo korekt",

  /* Zwroty */
  zwrot_paczki_klienta: "Paczka zwrotu przyjęta",
  zwrot_skan_dociagniecie: "Zwrot dociągnięty skanem",
  zwrot_zamowienia_kupujacego: "Zwrot z zamówienia kupującego",
  zwroty_zamowienia_reczne: "Zwrot z zamówienia wpisany ręcznie",
  zwrot_nieodebrana: "Paczka nieodebrana",
  zwrot_pozycja_dopisana: "Pozycja zwrotu dopisana",
  zwrot_pozycja_zdjeta: "Pozycja zwrotu zdjęta",
  zwrot_ilosc_zwrocona: "Ilość zwrócona zmieniona",
  zwrot_kartoteka: "Kartoteka zwrotu wskazana",
  zwrot_kartoteka_zdjeta: "Kartoteka zwrotu zdjęta",
  zwrot_ocena: "Ocena stanu zwrotu",
  zwrot_ocena_cofnieta: "Ocena stanu zwrotu cofnięta",
  zwrot_werdykt_przyjety: "Zwrot przyjęty",
  zwrot_werdykt_odrzucony: "Zwrot odrzucony",
  zwrot_werdykt_cofniety: "Decyzja o zwrocie cofnięta",
  zwrot_kwota: "Kwota zwrotu ustalona",
  zwrot_kwota_cofnieta: "Kwota zwrotu cofnięta",
  zwrot_potracenie: "Potrącenie ze zwrotu",
  zwrot_potracenie_cofniete: "Potrącenie ze zwrotu cofnięte",
  zwrot_pieniadze_oddane: "Pieniądze oddane",
  zwrot_pieniadze_odmowa: "Odmowa oddania pieniędzy",
  zwrot_wyplata_potwierdzona: "Wypłata zwrotu potwierdzona",
  zwrot_przelew: "Przelew zwrotu",
  zwrot_przelew_cofniety: "Przelew zwrotu cofnięty",
  zwrot_korekta: "Korekta do zwrotu",
  zwrot_korekta_cofnieta: "Korekta do zwrotu cofnięta",
  zwrot_faktura: "Faktura do zwrotu",
  zwrot_faktura_cofnieta: "Faktura do zwrotu cofnięta",
  zwrot_zw_zlecony: "Dokument ZW zlecony",
  zwrot_rabat_zgloszony: "Rabat do zwrotu zgłoszony",
  zwrot_rabat_automat_blad: "Automat rabatu zwrotu zawiódł",
  zwrot_outlet_przeniesiony: "Zwrot przeniesiony na outlet",
  zwrot_notatka: "Notatka do zwrotu",
  zwrot_notatka_cofnieta: "Notatka do zwrotu cofnięta",
  zwrot_notatka_zdjeta: "Notatka do zwrotu zdjęta",
  zwroty_synchronizacja_reczna: "Zwroty odświeżone ręcznie",
  zwroty_rozliczone_skasowane: "Rozliczone zwroty skasowane",
  zwroty_wyczyszczone: "Zwroty wyczyszczone",

  /* Skrzynka */
  rozmowa_przejeta: "Rozmowa przejęta",
  rozmowa_zwolniona: "Rozmowa zwolniona",
  rozmowa_przekazana_wymuszenie: "Rozmowa przejęta mimo kolegi",
  rozmowa_przypisana_odpowiedzia: "Rozmowa przypisana odpowiedzią",
  rozmowa_status: "Stan rozmowy zmieniony",
  rozmowa_priorytet: "Rozmowa oznaczona jako pilna",
  rozmowa_reklamacyjna: "Rozmowa oznaczona jako reklamacyjna",
  rozmowa_odlozona: "Rozmowa odłożona",
  rozmowa_komentarz: "Notatka w rozmowie",
  rozmowa_szkic_zapisany: "Szkic odpowiedzi zapisany",
  rozmowa_wysylka_proba: "Wysyłka odpowiedzi rozpoczęta",
  rozmowa_wyslana: "Odpowiedź wysłana",
  rozmowa_wysylka_cofnieta: "Wysyłka cofnięta",
  rozmowa_wysylka_blad: "Wysyłka odpowiedzi nie wyszła",
  rozmowa_wysylka_niepewna: "Wysyłka odpowiedzi niepewna",
  rozmowa_wysylka_konflikt: "Wysyłka w konflikcie",
  rozmowa_wysylka_uzgodniona: "Wysyłka uzgodniona z Allegro",
  rozmowa_zalacznik_dodany: "Załącznik dodany do odpowiedzi",
  rozmowa_zalacznik_zdjety: "Załącznik zdjęty z odpowiedzi",
  rozmowa_zakonczenie_cofniete: "Zakończenie rozmowy cofnięte",
  rozmowa_przeczytana_blad: "Oznaczenie przeczytania nie weszło",
  rozmowa_oferta_wskazana: "Oferta wskazana w rozmowie",
  rozmowa_kartoteka_wskazana: "Kartoteka wskazana w rozmowie",
  rozmowa_kartoteka_zdjeta: "Kartoteka zdjęta z rozmowy",
  rozmowa_zamowienie_wskazane: "Zamówienie wskazane w rozmowie",
  rozmowa_przesylka_reczna: "Przesyłka wpisana ręcznie",
  skrzynka_synchronizacja_reczna: "Skrzynka odświeżona ręcznie",
  wzmianka_odhaczona: "Wzmianka odhaczona",
  zamowienie_przesylka: "Przesyłka zamówienia",
  "obsluga.zalacznik.pobrany": "Załącznik klienta pobrany",
  allegro_zamowienie_brak: "Brak zamówienia w Allegro",

  /* Klient i sprawa klienta */
  klient_notatka: "Notatka o kliencie",
  klient_notatka_cofnieta: "Notatka o kliencie cofnięta",
  klient_notatka_zdjeta: "Notatka o kliencie zdjęta",
  klient_sprawa_krok: "Następny krok w sprawie klienta",
  klient_sprawa_przejeta: "Sprawa klienta przejęta",
  klient_sprawa_wznowiona: "Sprawa klienta wznowiona",
  klient_sprawa_zakonczona: "Sprawa klienta zakończona",
  klient_dosylka_zalozona: "Dosyłka założona",
  klient_dosylka_numer: "Numer dosyłki wpisany",
  klient_dosylka_wykryta: "Numer dosyłki wykryty",
  klient_dosylka_stan: "Stan dosyłki zmieniony",
  klient_dosylka_doreczona: "Dosyłka doręczona",
  klient_dosylka_problem: "Kłopot z dosyłką",

  /* Reklamacje */
  reklamacja_prowadzi: "Reklamacja przejęta",
  reklamacja_odswiezenie: "Reklamacja odświeżona z Allegro",
  reklamacja_rozpoznanie: "Reklamacja rozpoznana",
  reklamacja_odpowiedz: "Odpowiedź w reklamacji",
  reklamacja_wysylka_proba: "Wysyłka w reklamacji rozpoczęta",
  reklamacja_wysylka_konflikt: "Wysyłka w reklamacji w konflikcie",
  reklamacja_werdykt_proba: "Werdykt reklamacji wysyłany",
  reklamacja_werdykt: "Werdykt reklamacji",
  reklamacja_zwrot_towaru: "Zwrot towaru w reklamacji",
  reklamacja_przesylka_reczna: "Przesyłka reklamacji wpisana ręcznie",
  reklamacja_notatka: "Notatka w reklamacji",
  reklamacja_notatka_cofnieta: "Notatka w reklamacji cofnięta",
  reklamacja_zalacznik_dodany: "Załącznik dodany do reklamacji",
  reklamacja_zalacznik_zdjety: "Załącznik zdjęty z reklamacji",
  reklamacja_zalacznik_pobrany: "Załącznik reklamacji pobrany",
  reklamacja_zalacznik_bez_location: "Załącznik reklamacji bez adresu",
  reklamacje_synchronizacja_reczna: "Reklamacje odświeżone ręcznie",

  /* Dyskusje */
  dyskusja_prowadzi: "Dyskusja przejęta",
  dyskusja_odswiezenie: "Dyskusja odświeżona z Allegro",
  dyskusja_odpowiedz: "Odpowiedź w dyskusji",
  dyskusja_zakonczenie: "Dyskusja zakończona",
  dyskusja_przesylka_reczna: "Przesyłka dyskusji wpisana ręcznie",
  dyskusja_notatka: "Notatka w dyskusji",
  dyskusja_notatka_cofnieta: "Notatka w dyskusji cofnięta",
  dyskusja_zalacznik_dodany: "Załącznik dodany do dyskusji",
  dyskusja_zalacznik_zdjety: "Załącznik zdjęty z dyskusji",

  /* Tagi spraw */
  sprawa_tag_utworzony: "Tag utworzony",
  sprawa_tag_nazwa: "Tag przemianowany",
  sprawa_tag_wlaczony: "Tag włączony",
  sprawa_tag_wylaczony: "Tag wyłączony",
  sprawa_tag_przypiety: "Tag przypięty do sprawy",
  sprawa_tag_zdjety: "Tag zdjęty ze sprawy",

  /* Copilot */
  copilot_pytanie: "Pytanie do Copilota",
  copilot_szkic: "Szkic Copilota",
  copilot_szkic_ocena: "Szkic Copilota oceniony",
  copilot_szkic_po_rozpoznaniu: "Szkic Copilota po rozpoznaniu",
  copilot_auto_szkic: "Szkic Copilota w tle",
  copilot_auto_szkic_sufit: "Szkice w tle wstrzymane limitem",
  copilot_przed_praca: "Szkic przed pracą",
  copilot_klasyfikacja: "Rozpoznanie rozmowy przez Copilota",
  copilot_auto_klasyfikacja: "Rozpoznanie w tle",
  copilot_auto_klasyfikacja_sufit: "Rozpoznania w tle wstrzymane limitem",
  copilot_klasyfikacja_niepoprawna: "Rozpoznanie Copilota poprawione",
  copilot_korekta: "Poprawka odpowiedzi Copilota",
  copilot_dane_doboru: "Dane doboru dla Copilota",
  copilot_pasowanie: "Pasowanie od Copilota",
  copilot_pasowanie_z_sieci: "Pasowanie Copilota z sieci",
  klasyfikacja_mapowanie_do_przegladu: "Rozpoznanie do przeglądu",

  /* Dobór części */
  dobor_dane: "Dane doboru zapisane",
  dobor_status: "Stan doboru zmieniony",
  dobor_wybor: "Część dobrana",
  dobor_wybor_zdjety: "Dobór cofnięty",

  /* Wiedza */
  wiedza_propozycja: "Propozycja wiedzy",
  wiedza_rozstrzygniecie: "Propozycja wiedzy rozstrzygnięta",
  wiedza_wycofanie: "Wiedza wycofana",
  wiedza_dowod: "Dowód do wiedzy",
  wiedza_automat_przebieg: "Przebieg automatu wiedzy",
  wiedza_identyfikator_dodany: "Identyfikator dodany do wiedzy",
  wiedza_identyfikator_z_oferty_cofniety: "Identyfikator z oferty cofnięty",
  wiedza_model_utworzony: "Model utworzony",
  wiedza_model_z_opisu_odrzucony: "Model z opisu odrzucony",
  wiedza_model_z_opisu_przerobiony: "Model z opisu przerobiony",
  wiedza_z_oferty_zapisana: "Wiedza z oferty zapisana",
  pasowanie_propozycja: "Propozycja pasowania",
  pasowanie_rozstrzygniecie: "Pasowanie rozstrzygnięte",
  pasowanie_wycofanie: "Pasowanie wycofane",
  pasowanie_siec: "Pasowanie z sieci",
  pasowanie_siec_zatwierdzenie: "Pasowanie z sieci zatwierdzone",
  pasowanie_siec_potwierdzone: "Pasowanie z sieci potwierdzone",
  pasowanie_siec_silnik: "Pasowanie silnika z sieci",
  pasowanie_siec_silnik_zatwierdzenie: "Pasowanie silnika z sieci zatwierdzone",
  pasuje_do_lista: "Lista „pasuje do”",
  pasuje_do_zbiorka: "Zbiórka „pasuje do”",
  zabudowa_propozycja: "Propozycja zabudowy",
  zabudowa_rozstrzygniecie: "Zabudowa rozstrzygnięta",
  zabudowa_wycofanie: "Zabudowa wycofana",
  token_silnika_dodany: "Oznaczenie silnika dodane",
  token_silnika_usuniety: "Oznaczenie silnika usunięte",
  token_silnika_rozstrzygniecie: "Oznaczenie silnika rozstrzygnięte",
  alias_silnika_dodany: "Alias silnika dodany",
  alias_silnika_usuniety: "Alias silnika usunięty",
  wykaz_import: "Wykaz wczytany",
  wykaz_zatwierdzenie: "Wykaz zatwierdzony",
  wykaz_wycofanie: "Wykaz wycofany",
  zamiennosc_oem_rozstrzygniecie: "Zamienność OEM rozstrzygnięta",
  zamiennosc_oem_wycofanie: "Zamienność OEM wycofana",
  odsylacze_import: "Odsyłacze wczytane",
  odsylacze_wycofanie: "Odsyłacze wycofane",
  oferta_komplet_ustalony: "Komplet oferty ustalony",
  zbiorki_import: "Zbiórki wczytane",

  /* Konta, ustawienia, system */
  login: "Logowanie",
  login_failed: "Nieudane logowanie",
  user_created: "Konto założone",
  user_active_changed: "Konto włączone albo wyłączone",
  user_haslo_changed: "Hasło zmienione",
  user_wylogowany_wszedzie: "Wylogowanie ze wszystkich urządzeń",
  privileged: "Operacja uprzywilejowana",
  firma_zapis: "Dane firmy zapisane",
  logo_dostawcy_zapis: "Logo dostawcy zapisane",
  logo_dostawcy_usuniecie: "Logo dostawcy usunięte",
  strefa_zapis: "Reguły strefy zapisane",
  magazyny_widocznosc: "Widoczność magazynów zmieniona",
  konfiguracja_zmieniona: "Konfiguracja serwera zmieniona",
  allegro_polaczono: "Konto Allegro połączone",
  allegro_rozlaczono: "Konto Allegro rozłączone",
  aktualizacja_zlecona: "Aktualizacja zlecona",
  aktualizacja_automatyczna: "Aktualizacja automatyczna",
  aktualizacja_wynik: "Wynik aktualizacji",
  kopia_bazy: "Kopia bazy",
  rekoncyliacja: "Rekoncyliacja",
  sonda_rzeczywistosci: "Test na żywym Allegro",
  read_model_po_imporcie: "Przeliczenie po imporcie",
  migawka_dnia: "Migawka dnia",
  raport_tygodnia: "Raport tygodnia",
  audyt_eksport: "Dziennik pobrany do CSV",
  analiza_eksport: "Analiza pobrana do pliku",
};

/**
 * Pomiary i przeliczenia, które nie są niczyją czynnością. Dziennik chowa je
 * domyślnie, bo pomiar czasu skanu potrafi być co trzecim wierszem i zakopuje
 * błędy. Liczy je Analiza → Ergonomia; tu jeden klik je pokazuje.
 */
export const TECHNICZNE: readonly string[] = [
  "scan_timing", "czasy_zadan", "read_model_po_imporcie", "migawka_dnia",
];

/** Nazwa zdarzenia po polsku; typ spoza słownika wraca surowym kluczem. */
export const nazwaZdarzenia = (typ: string): string => NAZWA_ZDARZENIA[typ] ?? typ;
