/* ── Rejestr typów zdarzeń (23 września 2026) ────────────────────────────────
   Raport „czego nikt nie używa" (`uzycie.ts`) potrzebuje listy WSZYSTKIEGO,
   co panel i kolektor umieją zapisać. Sam dziennik jej nie zna: funkcja, której
   nikt nigdy nie nacisnął, nie zostawiła w nim ani jednego wiersza — a to jest
   dokładnie ta, o którą raport pyta.

   LISTĘ PILNUJE TEST, nie pamięć. `uzycie.test.ts` czyta źródła serwera
   i każdy literał w pierwszym argumencie `logEvent(...)` musi tu stać.
   Nowe zdarzenie bez wpisu to czerwony test, nie cicha dziura w raporcie.

   Typy składane w locie wpisane są ręcznie, z miejscem pochodzenia:
   `zwrot_werdykt_${decyzja}` (zwroty.ts), notatki spraw (reklamacje.ts),
   ślady doboru (dobor.ts), zadania workera (worker/kolejka.ts) i zdarzenia
   kolektora z `ALLOWED` w routes/device.ts. Czego nie ma w rejestrze, a jest
   w dzienniku, raport pokazuje osobno — nic nie ginie po cichu. */

export const ZDARZENIA: readonly string[] = [
  "alias_silnika_dodany", "alias_silnika_usuniety", "allegro_polaczono", "allegro_rozlaczono",
  "allegro_zamowienie_brak", "aktualizacja_automatyczna", "aktualizacja_wynik", "aktualizacja_zlecona", "analiza_eksport", "audyt_eksport", "battery_low",
  "brak_na_serwis", "brak_na_serwis_pominiety", "copilot_auto_klasyfikacja",
  "copilot_auto_klasyfikacja_sufit", "copilot_auto_szkic", "copilot_auto_szkic_sufit",
  "copilot_dane_doboru", "copilot_klasyfikacja", "copilot_klasyfikacja_niepoprawna",
  "copilot_korekta", "copilot_pasowanie", "copilot_pytanie", "copilot_szkic",
  "copilot_szkic_ocena", "copilot_szkic_po_rozpoznaniu", "czasy_zadan", "delivery_done", "delivery_external",
  "delivery_external_undo",
  "delivery_finished", "delivery_note_added", "delivery_note_answered", "delivery_open",
  "delivery_reopened", "device_drop", "dobor_dane", "dobor_status", "dobor_wybor",
  "dobor_wybor_zdjety", "dyskusja_notatka", "dyskusja_notatka_cofnieta", "dyskusja_odpowiedz",
  "dyskusja_odswiezenie", "dyskusja_zalacznik_dodany", "dyskusja_zalacznik_zdjety",
  "dyskusja_prowadzi", "dyskusja_przesylka_reczna", "dyskusja_zakonczenie", "ean_conflict",
  "ean_conflict_autoresolved", "ean_kolizja_rozstrzygnieta", "ean_set", "firma_zapis",
  "http_rejected", "karton_anulowany", "karton_ilosc", "karton_pozycja",
  "karton_pozycja_usunieta", "karton_zalozony", "karton_zatwierdzony",
  "klasyfikacja_mapowanie_do_przegladu", "konfiguracja_zmieniona", "kopia_bazy", "klient_notatka", "klient_notatka_cofnieta", "klient_notatka_zdjeta", "klient_odrzucona", "kolektor_odnaleziony",
  "kolektor_wezwanie_odwolane", "kolektor_wezwany", "kosz_mm_ponowione", "kosz_pominiecie_cofniete",
  "kosz_pominiecie_zalatwione", "kosz_powrot_mm", "kosz_pozycja_na_pozniej",
  "kosz_pozycja_pominieta", "kosz_putaway", "kosz_putaway_cofniete", "kosz_putaway_poprawka",
  "kosz_rozlozony", "kosz_zakonczenie_cofniete", "kosz_zwrotow_dolozono",
  "kosz_zwrotow_mm_mimo_korekt", "kosz_zwrotow_mm_uniewazniona", "kosz_zwrotow_odmowa",
  "kosz_zwrotow_otwarty", "kosz_zwrotow_przeliczony", "kosz_zwrotow_skladnik",
  "kosz_zwrotow_towar_dolozony", "kosz_zwrotow_towar_zdjety", "kosz_zwrotow_usuniety",
  "kosz_zwrotow_wypuszczony", "kosz_zwrotow_zamkniety", "kosz_zwrotow_zdjeto",
  "kosz_zwrotow_zwiazanie_pominiete", "kosz_zwrotow_zwiazany", "location_mismatch",
  "location_removed", "location_set", "login", "login_failed", "logo_dostawcy_usuniecie",
  "logo_dostawcy_zapis", "magazyny_widocznosc", "manual_entry", "migawka_dnia",
  "notatka_odpowiedz_przeczytana", "obsluga.zalacznik.pobrany", "odsylacze_import",
  "odsylacze_wycofanie", "oferta_komplet_ustalony", "pasowanie_propozycja",
  "pasowanie_rozstrzygniecie", "pasowanie_wycofanie", "pasuje_do_lista", "pasuje_do_zbiorka", "privileged", "problem_raised",
  "problem_resolved", "problem_wycofany", "przesuniecie", "przesylka_zapisana",
  "przyjecie_otwarte", "przyjecie_poza_aplikacja", "putaway_cofniete", "putaway_line_done",
  "putaway_polka_zmieniona", "putaway_qty_fixed", "queue_anulowane_recznie", "queue_applied",
  "queue_failed", "queue_ponowione_recznie", "queue_retry", "raport_tygodnia", "read_model_po_imporcie",
  "reklamacja_notatka", "rekoncyliacja", "reklamacja_notatka_cofnieta", "reklamacja_odpowiedz",
  "reklamacja_odswiezenie", "reklamacja_prowadzi", "reklamacja_przesylka_reczna",
  "reklamacja_rozpoznanie", "reklamacja_werdykt", "reklamacja_werdykt_proba",
  "reklamacja_wysylka_konflikt", "reklamacja_wysylka_proba",
  "reklamacja_zalacznik_bez_location", "reklamacja_zalacznik_dodany",
  "reklamacja_zalacznik_pobrany", "reklamacja_zalacznik_zdjety", "reklamacja_zwrot_towaru",
  "reklamacje_synchronizacja_reczna", "rozmowa_kartoteka_wskazana", "rozmowa_kartoteka_zdjeta",
  "rozmowa_komentarz", "rozmowa_oferta_wskazana", "rozmowa_priorytet",
  "sonda_rzeczywistosci",
  "rozmowa_przeczytana_blad", "rozmowa_przejeta", "rozmowa_przekazana_wymuszenie",
  "rozmowa_przesylka_reczna", "rozmowa_przypisana_odpowiedzia", "rozmowa_reklamacyjna",
  "rozmowa_status", "rozmowa_szkic_zapisany", "rozmowa_wyslana", "rozmowa_wysylka_blad",
  "rozmowa_wysylka_cofnieta", "rozmowa_wysylka_konflikt", "rozmowa_wysylka_niepewna", "rozmowa_wysylka_proba",
  "rozmowa_wysylka_uzgodniona", "rozmowa_zalacznik_dodany", "rozmowa_zalacznik_zdjety",
  "rozmowa_zakonczenie_cofniete", "rozmowa_zamowienie_wskazane", "rozmowa_zwolniona", "scan", "scan_timing", "search",
  "siec_przerwa", "skrzynka_synchronizacja_reczna", "sprawa_tag_nazwa", "sprawa_tag_przypiety",
  "sprawa_tag_utworzony", "sprawa_tag_wlaczony", "sprawa_tag_wylaczony", "sprawa_tag_zdjety",
  "strefa_zapis", "token_silnika_dodany", "token_silnika_rozstrzygniecie",
  "token_silnika_usuniety", "user_active_changed", "user_created", "user_haslo_changed",
  "user_wylogowany_wszedzie", "wiedza_automat_przebieg", "wiedza_dowod",
  "wiedza_identyfikator_dodany", "wiedza_identyfikator_z_oferty_cofniety",
  "wiedza_model_utworzony", "wiedza_model_z_opisu_odrzucony",
  "wiedza_model_z_opisu_przerobiony", "wiedza_propozycja", "wiedza_rozstrzygniecie",
  "pasowanie_siec",
  "wiedza_wycofanie", "wiedza_z_oferty_zapisana", "wykaz_import", "wykaz_wycofanie", "wykaz_zatwierdzenie", "wzmianka_odhaczona", "zabudowa_propozycja",
  "zabudowa_rozstrzygniecie", "zabudowa_wycofanie", "zadanie_terenowe_anulowane",
  "zadanie_terenowe_oddane", "zadanie_terenowe_odeslane", "zadanie_terenowe_ponowione",
  "zadanie_terenowe_przejete", "zadanie_terenowe_utworzone", "zadanie_terenowe_wykonane",
  "zadanie_terenowe_zalacznik", "zamiennosc_oem_rozstrzygniecie", "zamiennosc_oem_wycofanie",
  "zamowienie_przesylka", "zbiorki_import", "zdjecie_dodane", "zwrot_faktura",
  "zwrot_faktura_cofnieta", "zwrot_ilosc_zwrocona", "zwrot_kartoteka",
  "zwrot_kartoteka_zdjeta", "zwrot_korekta", "zwrot_korekta_cofnieta", "zwrot_kwota",
  "zwrot_kwota_cofnieta", "zwrot_nieodebrana", "zwrot_notatka", "zwrot_notatka_cofnieta",
  "zwrot_notatka_zdjeta", "zwrot_ocena", "zwrot_ocena_cofnieta", "zwrot_outlet_przeniesiony",
  "zwrot_paczki_klienta", "zwrot_pieniadze_oddane", "zwrot_pieniadze_odmowa",
  "zwrot_potracenie", "zwrot_potracenie_cofniete", "zwrot_pozycja_dopisana",
  "zwrot_pozycja_zdjeta", "zwrot_przelew", "zwrot_przelew_cofniety",
  "zwrot_rabat_automat_blad", "zwrot_rabat_zgloszony", "zwrot_skan_dociagniecie",
  "zwrot_werdykt_cofniety", "zwrot_werdykt_odrzucony", "zwrot_werdykt_przyjety",
  "zwrot_wyplata_potwierdzona", "zwrot_zamowienia_kupujacego", "zwrot_zw_zlecony",
  "zwroty_rozliczone_skasowane", "zwroty_synchronizacja_reczna", "zwroty_wyczyszczone",
  "zwroty_zamowienia_reczne",
];
