import { useEffect, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import { QueryClient, QueryClientProvider, useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useVirtualizer } from "@tanstack/react-virtual";

type Conversation={id:string;klient:string;temat:string;ostatniaWiadomosc:string;updatedAt:string;unread:boolean};
type Message={id:string;autor:"klient"|"agent"|"system";tresc:string;utworzono:string;offerId:string|null;offerTitle:string|null;twId:number|null;productName:string|null;kind:"message"|"field_result";fieldTaskId?:number;result?:string};
type Detail={conversation:Conversation;messages:Message[]};
const token=localStorage.getItem("wertis.token")||"";
async function api<T>(url:string, init?:RequestInit):Promise<T>{const r=await fetch(url,{...init,headers:{"x-session":token,...(init?.body?{"content-type":"application/json"}:{}),...init?.headers}});const d=await r.json().catch(()=>({})) as {error?:string};if(!r.ok)throw new Error(d.error||`Błąd ${r.status}`);return d as T}
const date=(v:string)=>new Intl.DateTimeFormat("pl-PL",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(v));

export function InboxList({active,onSelect}:{active:string|null;onSelect:(id:string)=>void}){
 const q=useQuery({queryKey:["inbox"],queryFn:()=>api<{conversations:Conversation[]}>("/api/obsluga/rozmowy"),refetchInterval:30000});
 const ref=useRef<HTMLDivElement>(null); const rows=q.data?.conversations||[];
 const virtual=useVirtualizer({count:rows.length,getScrollElement:()=>ref.current,estimateSize:()=>92,overscan:6});
 if(q.isLoading)return <aside className="inbox skeletons" aria-label="Ładowanie skrzynki">{[1,2,3,4,5].map(x=><i key={x}/>)}</aside>;
 if(q.isError)return <aside className="inbox state error"><b>Błąd synchronizacji</b><span>{q.error.message}</span><button onClick={()=>q.refetch()}>Spróbuj ponownie</button></aside>;
 if(!rows.length)return <aside className="inbox state"><b>Skrzynka jest pusta</b><span>Nie ma rozmów wymagających odczytu.</span></aside>;
 return <aside className="inbox" ref={ref}><div style={{height:virtual.getTotalSize(),position:"relative"}}>{virtual.getVirtualItems().map(v=>{const c=rows[v.index];return <button className="conversation" aria-current={c.id===active} key={c.id} onClick={()=>onSelect(c.id)} style={{position:"absolute",transform:`translateY(${v.start}px)`,height:v.size,width:"100%"}}><span className="who">{c.klient}{c.unread&&<i/>}</span><b>{c.temat}</b><small>{c.ostatniaWiadomosc}</small><time>{date(c.updatedAt)}</time></button>})}</div></aside>
}
export function OfferContext({message}:{message?:Message}){return <section className="context"><label>OFERTA</label>{message?.offerId?<><b>{message.offerTitle||"Oferta Allegro"}</b><span>nr {message.offerId}</span></>:<strong className="warning">Brak powiązania z ofertą</strong>}</section>}
export function ProductContext({message}:{message?:Message}){return <section className="context"><label>TOWAR</label>{message?.twId?<><b>{message.productName||message.offerTitle}</b><span>Kartoteka #{message.twId}</span></>:<span className="muted">Brak dopasowanej kartoteki</span>}</section>}
export function FieldTaskComposer({conversationId,source}:{conversationId:string;source?:Message}){const qc=useQueryClient();const m=useMutation({mutationFn:()=>api("/api/obsluga/zadania/pomiar",{method:"POST",body:JSON.stringify({conversationId,sourceMessageId:source?.id})}),onSuccess:()=>qc.invalidateQueries({queryKey:["conversation",conversationId]})});return <section className="field"><h3>Pomiar na hali</h3><p>Oferta, towar, rozmowa i wiadomość źródłowa zostaną dołączone automatycznie.</p><button disabled={!source?.offerId||!source.twId||m.isPending} onClick={()=>m.mutate()}>{m.isPending?"Zlecam…":"Zleć pomiar"}</button>{m.isSuccess&&<em>Zadanie trafiło do kolektora.</em>}{m.isError&&<strong>{m.error.message}</strong>}</section>}
export function ConversationComposer({draft,setDraft}:{draft:string;setDraft:(x:string)=>void}){return <section className="composer"><textarea value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Napisz szkic odpowiedzi…"/><div><span>Szkic lokalny — wysyłka do Allegro nie jest dostępna w tym wydaniu.</span><button disabled>Zapisz w Allegro</button></div></section>}
export function ConversationTimeline({messages,onInsert,onSource}:{messages:Message[];onInsert:(x:string)=>void;onSource:(m:Message)=>void}){const ref=useRef<HTMLDivElement>(null);const v=useVirtualizer({count:messages.length,getScrollElement:()=>ref.current,estimateSize:(i)=>messages[i].kind==="field_result"?150:130,overscan:5});useEffect(()=>v.scrollToIndex(messages.length-1,{align:"end"}),[messages.length]);return <div className="timeline" ref={ref}><div style={{height:v.getTotalSize(),position:"relative"}}>{v.getVirtualItems().map(row=>{const m=messages[row.index];return <article key={m.id} className={`message ${m.autor} ${m.kind}`} ref={v.measureElement} data-index={row.index} style={{position:"absolute",transform:`translateY(${row.start}px)`,width:"100%"}}>{m.kind==="field_result"?<><label>WEWNĘTRZNE · WYNIK Z KOLEKTORA</label><p>{m.result}</p><button onClick={()=>onInsert(m.result||"")}>Wstaw wynik do szkicu</button></>:<><header>{m.autor==="klient"?"Klient":"WERTIS"}<time>{date(m.utworzono)}</time></header><p>{m.tresc}</p>{m.autor==="klient"&&<button className="source" onClick={()=>onSource(m)}>Użyj jako źródła pomiaru</button>}</>}</article>})}</div></div>}
function App(){const initial=new URLSearchParams(location.search).get("rozmowa");const [active,setActive]=useState<string|null>(initial);const [draft,setDraft]=useState("");const [source,setSource]=useState<Message>();const detail=useQuery({queryKey:["conversation",active],queryFn:()=>api<Detail>(`/api/obsluga/rozmowy/${encodeURIComponent(active!)}`),enabled:!!active});function select(id:string){setActive(id);setSource(undefined);history.pushState({},"",`/obsluga/skrzynka?rozmowa=${encodeURIComponent(id)}`)}useEffect(()=>{const fn=()=>setActive(new URLSearchParams(location.search).get("rozmowa"));addEventListener("popstate",fn);return()=>removeEventListener("popstate",fn)},[]);const context=source||detail.data?.messages.find(m=>m.kind==="message"&&m.offerId);return <main><header className="top"><a href="/biuro">WERTIS</a><div><label>OBSŁUGA</label><h1>Skrzynka</h1></div><span>{localStorage.getItem("wertis.kto")}</span></header>{!token?<div className="login">Zaloguj się najpierw w <a href="/biuro">panelu biura</a>.</div>:<div className="workspace"><InboxList active={active} onSelect={select}/><section className="conversationPane">{!active?<div className="empty"><b>Wybierz rozmowę</b><span>Treść i kontekst pojawią się tutaj bez przeładowania strony.</span></div>:detail.isLoading?<div className="detailSkeleton skeletons"><i/><i/><i/></div>:detail.isError?<div className="empty error"><b>Błąd synchronizacji</b><span>{detail.error.message}</span><button onClick={()=>detail.refetch()}>Spróbuj ponownie</button></div>:detail.data&&<><header className="conversationHeader"><div><label>ROZMOWA</label><h2>{detail.data.conversation.temat}</h2><span>{detail.data.conversation.klient}</span></div></header><div className="detailGrid"><div className="thread"><ConversationTimeline messages={detail.data.messages} onInsert={x=>setDraft(d=>d+(d?"\n\n":"")+x)} onSource={setSource}/><ConversationComposer draft={draft} setDraft={setDraft}/></div><aside className="contexts"><OfferContext message={context}/><ProductContext message={context}/><FieldTaskComposer conversationId={active} source={source||detail.data.messages.find(m=>m.autor==="klient"&&!!m.offerId)}/></aside></div></>}</section></div>}</main>}
const client=new QueryClient({defaultOptions:{queries:{staleTime:15000,retry:1}}});createRoot(document.getElementById("root")!).render(<QueryClientProvider client={client}><App/></QueryClientProvider>);
